### ISSUE TITLE
Blank page and console errors

### ISSUE THREAD

**Issue by KristofferBroberg** [nachocinalli/adapt-gridMenu#1]
I've created one page with some dummy content and uploaded an image to the page's graphic. All get is an blank page (and the loader looks different, funny enough). I can preview the same course using the native box menu without problem.

- Node 16.20.2
- Framework 5.37.9
- AT 0.11.3

Console:
![image](https://github.com/nachocinalli/adapt-gridMenu/assets/5649735/e94c34f4-8c86-4d2d-9d80-1b2f2ab1f46b)

**Comment by nachocinalli** [comment]
Hi @KristofferBroberg, I cannot replicate the error. 
Could you share me the zip file using the export source option of the AAT?

**Comment by KristofferBroberg** [comment]
Sure!

[ny-kurs-export.zip](https://github.com/nachocinalli/adapt-gridMenu/files/15129199/ny-kurs-export.zip)

**Comment by nachocinalli** [comment]
It seems that the adapt-gridMenu was not installed correctly in your AAT.
The 'templates' folder is missing.

Could you uninstall the adapt-gridMenu and reinstall it?

**Comment by KristofferBroberg** [comment]
I reinstalled, but the templates folder was still missing. I then manually added it and that seem to do the trick?

**Comment by KristofferBroberg** [comment]
Oh wait...you need to add styling yourself, I suppose?

**Comment by KristofferBroberg** [comment]
I'm closing as I suppose the issue with the templates folder not getting installed has something to do with the AAT, not the plugin itself.

**Comment by nachocinalli** [comment]
Try adding these [styles ](https://github.com/nachocinalli/adapt-gridMenu?tab=readme-ov-file#theme-lesscss)in your custom css/less. Connect with me at [gitter](https://app.gitter.im/) if you need support.
